service: stock-alerter-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  stockAlerter:
    handler: bestbuy.ticketAlerter
    events:
      - schedule: rate(5 minutes)
      - schedule: cron(0 17 * * ? *)
    timeout: 60
    environment:
      ACCOUNT_SID: ${file(variables/variables.yaml):ACCOUNT_SID}
      AUTH_TOKEN: ${file(variables/variables.yaml):AUTH_TOKEN}
      MESSAGE_SERVICE_SID: ${file(variables/variables.yaml):MESSAGE_SERVICE_SID}
      PHONE_NUMBER: ${file(variables/variables.yaml):PHONE_NUMBER}
      MONTH_I_CARE: ${file(variables/variables.yaml):MONTH_I_CARE}
      DAYS_I_CARE: ${file(variables/variables.yaml):DAYS_I_CARE}
